admin_post:
    pattern:  /
    defaults: { _controller: "ACInst3BlogBundle:Post:index" }

admin_post_show:
    pattern:  /{id}/show
    defaults: { _controller: "ACInst3BlogBundle:Post:show" }

admin_post_new:
    pattern:  /new
    defaults: { _controller: "ACInst3BlogBundle:Post:new" }

admin_post_create:
    pattern:  /create
    defaults: { _controller: "ACInst3BlogBundle:Post:create" }
    requirements: { _method: post }

admin_post_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ACInst3BlogBundle:Post:edit" }

admin_post_update:
    pattern:  /{id}/update
    defaults: { _controller: "ACInst3BlogBundle:Post:update" }
    requirements: { _method: post }

admin_post_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ACInst3BlogBundle:Post:delete" }
    requirements: { _method: post }
